test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
    args.default_access_level = "REPORTER"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.84343332.name = "Upgrade from (#28)"
