#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1

[default]

    test_upgrade_from.84343332e9cf5d359df6340df70d95a815c74df2.name = "Testing (#28)"
