#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

# Set permissions to app files
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R "$app:www-data" "$install_dir"
#=================================================
# SPECIFIC SETUP
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

random=$(ynh_string_random --length=20)

ynh_config_add --template="config_inc.php" --destination="$install_dir/config/config_inc.php"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R "$app:www-data" "$install_dir"
#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated PHP-FPM config
ynh_config_add_phpfpm

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# SETUP APPLICATION WITH CURL
#=================================================
ynh_script_progression "Setting up application with CURL..."

# Installation with cURL
ynh_local_curl "/admin/install.php?submit" \
    "install=2" "hostname=localhost" "timezone=UTC" \
    "admin_username=" "admin_password=" \
    "db_type=mysqli" "db_username=$db_user" "db_password=$db_pwd" "database_name=$db_name" \
    "db_table_prefix=$db_name" "db_table_plugin_prefix=plugin" "db_table_suffix=_table"

# Remove the `admin/` directory from within the MantisBT installation path.
# The scripts within this directory should not be accessible on a live MantisBT site
# or on any installation that is accessible via the Internet.
ynh_safe_rm "$install_dir/admin"

# Set the user chosen at installation as administrator
ynh_mysql_db_shell <<< "UPDATE ${db_name}_user_table SET username = '$admin' WHERE id = 1;"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
