#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message="Ensuring downward compatibility..." --weight=1

# If default_access_level doesn't exist, create it
if [ -z "${default_access_level:-}" ]; then
    default_access_level="REPORTER"
    ynh_app_setting_set --app="$app" --key="default_access_level" --value="$default_access_level"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Upgrading source files..." --weight=5

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir=$install_dir --full_replace=1 --keep="config"

# Set permissions to app files
chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# SETUP APPLICATION WITH CURL
#=================================================
ynh_script_progression --message="Finalizing installation with Curl..." --weight=10

# Installation with cURL
ynh_local_curl "/admin/install.php?submit" \
    "install=2" "hostname=localhost" "timezone=UTC" \
    "admin_username=" "admin_password=" \
    "db_type=mysqli" "db_username=$db_user" "db_password=$db_pwd" "database_name=$db_name" \
    "db_table_prefix=$db_name" "db_table_plugin_prefix=plugin" "db_table_suffix=_table"

# Remove the `admin/` directory from within the MantisBT installation path.
# The scripts within this directory should not be accessible on a live MantisBT site
# or on any installation that is accessible via the Internet.
ynh_secure_remove --file="$install_dir/admin"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Upgrading system configurations related to $app..." --weight=1

# Recreate a dedicated PHP-FPM config
ynh_add_fpm_config

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
